export const images=[
    { src: "/images/azure.png", alt: "azure" },
    { src: "/images/spring.png", alt: "spring" },
    { src: "/images/ansible.png", alt: "ansible" },
    { src: "/images/aws.png", alt: "aws" },
    { src: "/images/docker.png", alt: "docker" },
    { src: "/images/figma.png", alt: "figma" },
    { src: "/images/jenkins.png", alt: "jenkins" },
    { src: "/images/kubernetes.png", alt: "kubernetes" },
    { src: "/images/mongo.png", alt: "mongo" },
    { src: "/images/node.png", alt: "node" },
    { src: "/images/python.png", alt: "python" },
    { src: "/images/postgre.png", alt: "postgres" },
    { src: "/images/react.png", alt: "react" },
    { src: "/images/redis.png", alt: "redis" },
    { src: "/images/tf.png", alt: "tf" },
    { src: "/images/typescript.png", alt: "typescript" },
    { src: "/images/wordpress.png", alt: "wordpress" },
]