services:
  mysql:
    image: mysql:8.0.40-debian
    container_name: mysql
    ports:
      - "3306:3306"  
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - ./.env
volumes:
  mysql_data:
